#服务器配置
server: 
  port: 8088
#实体类扫描的包名
mybatis:
  type-aliases-package: com.example.demo.*.entity
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro
    username: root
    password: cope9020
    dbcp:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
#模板配置
  thymeleaf:
    check-template: false
    content-type: text/html
    encoding: UTF-8
#分页配置
pageSize: 15