debug: false
#服务器配置
server: 
  port: 8088
  session:
    persistent: true
#项目名称
spring:
  application:
    name: SpringBoot-Shiro-Demo
#数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/etao_v4
    username: root
    password: cope9020
    dbcp:
      #连接池的最大值
      max-active: 20
      #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
      max-idle: 8
      #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 8
      #连接池启动时的初始值
      initial-size: 10
#模板配置
  thymeleaf:
    cache: false
    check-template: false
    content-type: text/html
    encoding: UTF-8
#分页配置
pageSize: 25
#实体类扫描的包名
mybatis:
  type-aliases-package: com.jrsoft.*.entity
