debug: false
#服务器配置
server: 
  port: 8088
  session:
    persistent: true
#实体类扫描的包名
mybatis:
  type-aliases-package: com.jrsoft.*.entity
#数据源配置
spring:
  application:
    name: SpringBoot-Shiro-Demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro_auth?characterEncoding=utf-8
    #url: jdbc:mysql://127.0.0.1:3306/etao_v4?characterEncoding=utf-8
    username: root
    password: cope9020
    dbcp:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
#模板配置
  thymeleaf:
    cache: false
    check-template: false
    content-type: text/html
    encoding: UTF-8
#分页配置
pageSize: 25